#!/usr/bin/env python3
"""
Build session-aware dynamic volatility-adjusted triple-barrier targets.

Uses:
  canonical M1 OHLC
  session-aware active segments generated by
  build_session_aware_market_filter.py

Key difference from the earlier dynamic target:
- CLOSED/inactive flat runs are not used as market history.
- A volatility lookback cannot cross a closed-market period.
- A 60-minute future horizon cannot cross a closed-market period.
- Rows inside closed runs are marked SESSION_CLOSED (-3).
- Rows lacking sufficient active history/future are marked INVALID (-2).
- Same-bar upper/lower touch is AMBIGUOUS (-1).
- SHORT=0, TIMEOUT=1, LONG=2.

Barrier:
  multiplier × sigma_1m × sqrt(60)

Multipliers:
  0.50, 0.75, 1.00, 1.25, 1.50

2026 is generated for diagnostics only and must stay excluded from
later model selection/testing.
"""

from pathlib import Path
import math
import time
import numpy as np
import pandas as pd
from numba import njit

BASE = Path("data/processed")
CANONICAL = BASE / "xauusd_m1_2019_2026_canonical.csv"
SEGMENTS = BASE / "xauusd_m1_active_segments.csv"

OUTPUTS = {
    0.50: BASE / "xauusd_m1_session_dynamic_tb_0p50.csv",
    0.75: BASE / "xauusd_m1_session_dynamic_tb_0p75.csv",
    1.00: BASE / "xauusd_m1_session_dynamic_tb_1p00.csv",
    1.25: BASE / "xauusd_m1_session_dynamic_tb_1p25.csv",
    1.50: BASE / "xauusd_m1_session_dynamic_tb_1p50.csv",
}

SUMMARY = BASE / "xauusd_m1_session_dynamic_tb_summary.csv"

HORIZON = 60
LOOKBACK = 60
SQRT_HORIZON = math.sqrt(HORIZON)

SHORT = np.int8(0)
TIMEOUT = np.int8(1)
LONG = np.int8(2)
AMBIGUOUS = np.int8(-1)
INVALID = np.int8(-2)
SESSION_CLOSED = np.int8(-3)


@njit(cache=True)
def build_session_dynamic_tb(
    high, low, close, active_starts, active_ends, multiplier
):
    n = len(close)

    labels = np.full(n, SESSION_CLOSED, dtype=np.int8)
    exits = np.full(n, -1, dtype=np.int64)
    vol = np.full(n, np.nan, dtype=np.float64)
    barriers = np.full(n, np.nan, dtype=np.float64)

    for seg in range(len(active_starts)):
        s = int(active_starts[seg])
        e = int(active_ends[seg])

        # Need LOOKBACK previous returns plus HORIZON future bars.
        first = s + LOOKBACK
        last = e - HORIZON - 1

        # Active rows with insufficient history/future remain INVALID.
        if first >= e:
            for i in range(s, e):
                labels[i] = INVALID
            continue

        for i in range(s, min(first, e)):
            labels[i] = INVALID

        if last < first:
            for i in range(first, e):
                labels[i] = INVALID
            continue

        for i in range(last + 1, e):
            labels[i] = INVALID

        for i in range(first, last + 1):
            entry = close[i]

            if not np.isfinite(entry) or entry <= 0.0:
                labels[i] = INVALID
                continue

            hist = close[i - LOOKBACK - 1:i]

            if (
                len(hist) != LOOKBACK + 1
                or np.any(~np.isfinite(hist))
                or np.any(hist <= 0.0)
            ):
                labels[i] = INVALID
                continue

            rets = np.log(hist[1:] / hist[:-1])

            # Numba compatibility: manually compute sample standard deviation
            # (ddof=1), matching the intended volatility definition.
            mean_r = 0.0
            for k in range(LOOKBACK):
                mean_r += rets[k]
            mean_r /= LOOKBACK

            var = 0.0
            for k in range(LOOKBACK):
                d = rets[k] - mean_r
                var += d * d
            var /= (LOOKBACK - 1)

            sigma = math.sqrt(max(var, 0.0))

            if not np.isfinite(sigma) or sigma <= 0.0:
                labels[i] = INVALID
                continue

            barrier = multiplier * sigma * SQRT_HORIZON

            if not np.isfinite(barrier) or barrier <= 0.0:
                labels[i] = INVALID
                continue

            upper = entry * (1.0 + barrier)
            lower = entry * (1.0 - barrier)

            vol[i] = sigma
            barriers[i] = barrier

            outcome = TIMEOUT
            exit_i = i + HORIZON

            for j in range(i + 1, i + HORIZON + 1):
                hit_up = high[j] >= upper
                hit_down = low[j] <= lower

                if hit_up and hit_down:
                    outcome = AMBIGUOUS
                    exit_i = j
                    break
                elif hit_down:
                    outcome = SHORT
                    exit_i = j
                    break
                elif hit_up:
                    outcome = LONG
                    exit_i = j
                    break

            labels[i] = outcome
            exits[i] = exit_i

    return labels, exits, vol, barriers


def detect_epoch_unit(values):
    s = pd.to_numeric(values, errors="coerce")
    med = float(s.dropna().abs().median())
    if med >= 1e17:
        return "ns"
    if med >= 1e14:
        return "us"
    if med >= 1e11:
        return "ms"
    return "s"


def load_canonical():
    print("=" * 78)
    print("Loading canonical XAUUSD M1...")
    print("=" * 78)

    parts = []
    for chunk in pd.read_csv(
        CANONICAL,
        usecols=["timestamp", "open", "high", "low", "close"],
        chunksize=500_000,
    ):
        parts.append(chunk)

    df = pd.concat(parts, ignore_index=True)
    del parts

    ts_raw = pd.to_numeric(df["timestamp"], errors="coerce")
    if ts_raw.isna().any():
        raise ValueError("Invalid timestamps in canonical file.")

    unit = detect_epoch_unit(ts_raw)
    df["timestamp"] = ts_raw.astype(np.int64)

    for c in ["open", "high", "low", "close"]:
        df[c] = pd.to_numeric(df[c], errors="coerce").astype(np.float64)

    if not np.isfinite(df[["open", "high", "low", "close"]].to_numpy()).all():
        raise ValueError("Non-finite OHLC in canonical data.")

    ts = df["timestamp"].to_numpy(np.int64, copy=False)
    if not np.all(ts[1:] > ts[:-1]):
        raise ValueError("Canonical timestamps are not strictly increasing.")

    print(f"Rows loaded: {len(df):,}")
    print(f"Timestamp unit: epoch-{unit}")
    return df, unit


def load_active_segments(n_rows):
    print("\nLoading session-aware active segments...")
    seg = pd.read_csv(SEGMENTS)

    required = ["start_index", "end_index_exclusive", "length_minutes"]
    missing = [c for c in required if c not in seg.columns]
    if missing:
        raise KeyError(f"Missing segment columns: {missing}")

    starts = pd.to_numeric(seg["start_index"], errors="coerce").astype(np.int64).to_numpy()
    ends = pd.to_numeric(seg["end_index_exclusive"], errors="coerce").astype(np.int64).to_numpy()
    lengths = pd.to_numeric(seg["length_minutes"], errors="coerce").astype(np.int64).to_numpy()

    if len(starts) == 0:
        raise ValueError("No active segments found.")

    if np.any(starts < 0) or np.any(ends > n_rows) or np.any(ends <= starts):
        raise ValueError("Invalid active segment bounds.")

    if not np.all(ends[:-1] <= starts[1:]):
        raise ValueError("Active segments overlap or are out of order.")

    print(f"Active segments: {len(starts):,}")
    print(f"Active rows represented: {int(lengths.sum()):,}")
    print(
        f"Segments >= {LOOKBACK + HORIZON + 1} rows: "
        f"{int((lengths >= LOOKBACK + HORIZON + 1).sum()):,}"
    )
    return starts, ends


def run_one(df, active_starts, active_ends, multiplier):
    high = df["high"].to_numpy(np.float64, copy=False)
    low = df["low"].to_numpy(np.float64, copy=False)
    close = df["close"].to_numpy(np.float64, copy=False)

    return build_session_dynamic_tb(
        high, low, close, active_starts, active_ends, multiplier
    )


def summarize(df, labels, barriers, multiplier):
    total = len(labels)
    closed = int((labels == SESSION_CLOSED).sum())
    invalid = int((labels == INVALID).sum())
    ambiguous = int((labels == AMBIGUOUS).sum())
    short = int((labels == SHORT).sum())
    timeout = int((labels == TIMEOUT).sum())
    long = int((labels == LONG).sum())

    valid = short + timeout + long

    mean_bps = (
        float(np.nanmean(barriers[labels >= 0])) * 10000.0
        if valid > 0
        else np.nan
    )

    return {
        "multiplier": multiplier,
        "horizon_min": HORIZON,
        "vol_lookback_min": LOOKBACK,
        "total_rows": total,
        "session_closed_rows": closed,
        "invalid_rows": invalid,
        "ambiguous_rows": ambiguous,
        "valid_rows": valid,
        "short_rows": short,
        "timeout_rows": timeout,
        "long_rows": long,
        "short_pct_valid": short / valid * 100.0 if valid else np.nan,
        "timeout_pct_valid": timeout / valid * 100.0 if valid else np.nan,
        "long_pct_valid": long / valid * 100.0 if valid else np.nan,
        "mean_barrier_bps": mean_bps,
    }


def save_output(df, labels, exits, vol, barriers, path):
    out = df.copy()
    out["volatility_60m"] = vol
    out["barrier_return_60m"] = barriers
    out["tb_label_60m"] = labels
    out["tb_exit_index_60m"] = exits
    out.to_csv(path, index=False)


def main():
    print("=" * 78)
    print("SESSION-AWARE DYNAMIC TRIPLE-BARRIER TARGETS")
    print("=" * 78)
    print("Horizon: 60 minutes")
    print("Volatility lookback: previous 60 ACTIVE 1-minute returns")
    print("Closed-market runs are excluded from history and future windows.")
    print("Barrier = multiplier × sigma_1m × sqrt(60)")
    print("Multipliers: [0.50, 0.75, 1.00, 1.25, 1.50]")
    print("2026: diagnostic only")
    print("=" * 78)

    t0 = time.time()

    df, unit = load_canonical()
    if unit != "ms":
        raise ValueError(
            f"This project currently expects epoch-ms canonical timestamps; got {unit}."
        )

    active_starts, active_ends = load_active_segments(len(df))

    print("\nCompiling Numba engine...")
    # Use the first active segment long enough for 60m history + 60m future.
    eligible = np.flatnonzero(
        (active_ends - active_starts) >= (LOOKBACK + HORIZON + 1)
    )
    if eligible.size == 0:
        raise ValueError("No active segment is long enough for compilation.")
    j = int(eligible[0])
    _ = run_one(df, active_starts[j:j+1], active_ends[j:j+1], 1.0)
    print("Numba compilation complete.")

    summaries = []

    for multiplier, path in OUTPUTS.items():
        print("\n" + "=" * 78)
        print(f"MULTIPLIER {multiplier:.2f}x")
        print(f"Output: {path}")
        print("=" * 78)

        t1 = time.time()
        labels, exits, vol, barriers = run_one(
            df, active_starts, active_ends, multiplier
        )

        summary = summarize(df, labels, barriers, multiplier)
        summaries.append(summary)

        print(f"Session-closed: {summary['session_closed_rows']:,}")
        print(f"Invalid:        {summary['invalid_rows']:,}")
        print(f"Ambiguous:      {summary['ambiguous_rows']:,}")
        print(f"Valid:          {summary['valid_rows']:,}")
        print(f"SHORT:          {summary['short_rows']:,}")
        print(f"TIMEOUT:        {summary['timeout_rows']:,}")
        print(f"LONG:           {summary['long_rows']:,}")
        print(
            "Valid class %:  "
            f"[{summary['short_pct_valid']:.2f}, "
            f"{summary['timeout_pct_valid']:.2f}, "
            f"{summary['long_pct_valid']:.2f}]"
        )
        print(f"Mean barrier:   {summary['mean_barrier_bps']:.2f} bps")
        print(f"Elapsed:        {time.time() - t1:.2f} sec")

        save_output(df, labels, exits, vol, barriers, path)
        print(f"Saved: {path}")

    summary_df = pd.DataFrame(summaries)
    summary_df.to_csv(SUMMARY, index=False)

    print("\n" + "=" * 78)
    print("SESSION-AWARE DYNAMIC TARGET GENERATION COMPLETE")
    print("=" * 78)
    print(summary_df.to_string(index=False))
    print(f"\nSaved summary: {SUMMARY}")
    print(f"Total wall time: {time.time() - t0:.1f} sec")
    print("2026 is diagnostic only and must remain untouched for model selection.")
    print("=" * 78)


if __name__ == "__main__":
    main()
